import { AppointmentStatus, Prisma, SlotStatus } from "@prisma/client";
import { AppointmentNotFoundError, AppointmentOwnershipError, ReservationConflictError } from "@/lib/domain-errors";
import { prisma } from "@/lib/prisma";
const locks = new Map<string, Promise<void>>();
async function withLock<T>(slotId: string, work: () => Promise<T>) { const previous = locks.get(slotId) ?? Promise.resolve(); let release!: () => void; const current = new Promise<void>((resolve) => { release = resolve; }); locks.set(slotId, current); await previous; try { return await work(); } finally { release(); if (locks.get(slotId) === current) locks.delete(slotId); } }
const isUnique = (error: unknown) => error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002";
export async function reserveAppointment(input: { patientId: string; specialistId: string; slotId: string }) { return withLock(input.slotId, async () => { try { return await prisma.$transaction(async (tx) => { const patient = await tx.patient.findUnique({ where: { id: input.patientId } }); if (!patient) throw new AppointmentNotFoundError(); const claim = await tx.availabilitySlot.updateMany({ where: { id: input.slotId, specialistId: input.specialistId, status: SlotStatus.AVAILABLE }, data: { status: SlotStatus.BOOKED } }); if (claim.count !== 1) throw new ReservationConflictError(); return tx.appointment.create({ data: { ...input, status: AppointmentStatus.BOOKED }, include: { slot: true, specialist: { include: { specialty: true } } } }); }); } catch (error) { if (error instanceof ReservationConflictError || isUnique(error)) throw new ReservationConflictError(); throw error; } }); }
export async function cancelAppointment(input: { appointmentId: string; patientId: string }) { const found = await prisma.appointment.findUnique({ where: { id: input.appointmentId } }); if (!found) throw new AppointmentNotFoundError(); if (found.patientId !== input.patientId) throw new AppointmentOwnershipError(); return withLock(found.slotId, () => prisma.$transaction(async (tx) => { const current = await tx.appointment.findUnique({ where: { id: input.appointmentId } }); if (!current) throw new AppointmentNotFoundError(); if (current.patientId !== input.patientId) throw new AppointmentOwnershipError(); if (current.status === AppointmentStatus.CANCELLED) return current; const cancelled = await tx.appointment.update({ where: { id: current.id }, data: { status: AppointmentStatus.CANCELLED, cancelledAt: new Date() } }); await tx.availabilitySlot.updateMany({ where: { id: current.slotId, status: SlotStatus.BOOKED }, data: { status: SlotStatus.AVAILABLE } }); return cancelled; })); }
export async function listAppointmentsForPatient(patientId: string) { return prisma.appointment.findMany({ where: { patientId }, include: { specialist: { include: { specialty: true } }, slot: true }, orderBy: { createdAt: "desc" } }); }
