import { afterAll, beforeEach, describe, expect, it } from "vitest";
import { AppointmentStatus, SlotStatus } from "@prisma/client";
import { cancelAppointment, listAppointmentsForPatient, reserveAppointment } from "@/lib/appointments";
import { AppointmentOwnershipError, ReservationConflictError } from "@/lib/domain-errors";
import { prisma } from "@/lib/prisma";
import { searchSpecialists } from "@/lib/specialists";
import { seedDatabase } from "../scripts/seed";
beforeEach(async () => { await prisma.appointment.deleteMany(); await prisma.availabilitySlot.deleteMany(); await prisma.specialist.deleteMany(); await prisma.specialty.deleteMany(); await prisma.patient.deleteMany(); await seedDatabase(prisma); });
afterAll(() => prisma.$disconnect());
async function fixture() { const patient = await prisma.patient.findUniqueOrThrow({ where: { email: "paciente.cinco@example.test" } }); const other = await prisma.patient.findUniqueOrThrow({ where: { email: "paciente.seis@example.test" } }); const slot = await prisma.availabilitySlot.findFirstOrThrow({ where: { status: SlotStatus.AVAILABLE }, include: { specialist: true } }); return { patient, other, slot }; }
describe("fictional appointment domain", () => {
  it("filters by text, specialty, city and modality", async () => { const results = await searchSpecialists({ text: "Aster", specialtySlug: "aurora", city: "Buenos Aires", modality: "VIRTUAL" }); expect(results).toHaveLength(1); expect(results[0]?.firstName).toBe("Ada"); });
  it("reserves a valid available slot and lists it for the patient", async () => { const { patient, slot } = await fixture(); const appointment = await reserveAppointment({ patientId: patient.id, specialistId: slot.specialistId, slotId: slot.id }); expect(appointment.status).toBe(AppointmentStatus.BOOKED); expect(await listAppointmentsForPatient(patient.id)).toHaveLength(1); });
  it("allows exactly one concurrent reservation for a slot", async () => { const { patient, other, slot } = await fixture(); const attempts = await Promise.allSettled([reserveAppointment({ patientId: patient.id, specialistId: slot.specialistId, slotId: slot.id }), reserveAppointment({ patientId: other.id, specialistId: slot.specialistId, slotId: slot.id })]); expect(attempts.filter((attempt) => attempt.status === "fulfilled")).toHaveLength(1); expect(attempts.filter((attempt) => attempt.status === "rejected" && attempt.reason instanceof ReservationConflictError)).toHaveLength(1); });
  it("cancels, releases and rebooks while retaining the cancelled row", async () => { const { patient, other, slot } = await fixture(); const first = await reserveAppointment({ patientId: patient.id, specialistId: slot.specialistId, slotId: slot.id }); const cancelled = await cancelAppointment({ appointmentId: first.id, patientId: patient.id }); expect(cancelled.status).toBe(AppointmentStatus.CANCELLED); expect((await prisma.availabilitySlot.findUniqueOrThrow({ where: { id: slot.id } })).status).toBe(SlotStatus.AVAILABLE); await reserveAppointment({ patientId: other.id, specialistId: slot.specialistId, slotId: slot.id }); expect(await prisma.appointment.count({ where: { slotId: slot.id, status: AppointmentStatus.CANCELLED } })).toBe(1); expect(await prisma.appointment.count({ where: { slotId: slot.id, status: AppointmentStatus.BOOKED } })).toBe(1); });
  it("does not let a different patient cancel", async () => { const { patient, other, slot } = await fixture(); const appointment = await reserveAppointment({ patientId: patient.id, specialistId: slot.specialistId, slotId: slot.id }); await expect(cancelAppointment({ appointmentId: appointment.id, patientId: other.id })).rejects.toBeInstanceOf(AppointmentOwnershipError); expect((await prisma.appointment.findUniqueOrThrow({ where: { id: appointment.id } })).status).toBe(AppointmentStatus.BOOKED); });
});
